name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sunriseduarte/450-tictactest-mvk:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4

      - run: ./gradlew build -x test

  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sunriseduarte/450-tictactest-mvk:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4

      - run: ./gradlew test
